name: Kafka Workflow

on:
  workflow_dispatch:
    inputs:
      topic:
        description: 'Kafka Topic'
        required: true
        default: 'pizza'

jobs:
  kafka-bridge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Spin-Up Docker Compose
        uses: s3i7h/spin-up-docker-compose-action@v1.2
        with:
          file:  docker-compose.yml
          
      - name: Wait for Kafka to be ready
        run: |
          sleep 30  # Ajusta este tiempo si es necesario para que Kafka esté listo

      - name: Run the Kafka producer/consumer script
        run: |
          python run.py --topic=${{ github.event.inputs.topic }} --num_messages=50 --num_partitions=2
